# Generated by Django 5.2.14 on 2026-05-26 16:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_object_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('LOCK', 'Lock for auditor'), ('FLAG', 'Flag for further review')], db_index=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Review Action',
                'verbose_name_plural': 'Review Actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
