# Generated by Django 5.2.14 on 2026-05-26 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewaction',
            name='analyst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewaction',
            name='row_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='reviewaction',
            index=models.Index(fields=['row_content_type', 'row_object_id'], name='review_revi_row_con_743c6b_idx'),
        ),
    ]
