# Generated by Django 5.2.14 on 2026-05-26 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Used in URLs — auto-generated from name', max_length=100, unique=True)),
                ('industry', models.CharField(blank=True, help_text='e.g. Manufacturing, Logistics, Technology', max_length=100)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2 e.g. IN, DE, GB', max_length=2)),
                ('subscription_plan', models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin — full access including user management'), ('ANALYST', 'Analyst — can view, upload, approve, reject rows'), ('AUDITOR', 'Auditor — read-only, LOCKED rows only'), ('VIEWER', 'Viewer — read-only, approved and locked rows')], default='ANALYST', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Organisation Membership',
                'verbose_name_plural': 'Organisation Memberships',
                'ordering': ['organisation__name', 'role'],
            },
        ),
    ]
