# Generated by Django 5.2.14 on 2026-05-26 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportlookup',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_lookups', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='gridemissionfactor',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_emission_factors', to='organisations.organisation'),
        ),
    ]
