# Generated by Django 5.2.14 on 2026-05-26 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0002_initial'),
        ('ingestion', '0002_initial'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plantlookup',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_lookups_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantlookup',
            name='grid_emission_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.gridemissionfactor'),
        ),
        migrations.AddField(
            model_name='plantlookup',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_lookups', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='saprow',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='saprow',
            name='raw_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rows', to='ingestion.rawupload'),
        ),
        migrations.AddField(
            model_name='travelemissionfactor',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_emission_factors', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='travelrow',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='travelrow',
            name='raw_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rows', to='ingestion.rawupload'),
        ),
        migrations.AddField(
            model_name='utilityrow',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='utilityrow',
            name='raw_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rows', to='ingestion.rawupload'),
        ),
        migrations.AlterUniqueTogether(
            name='airportlookup',
            unique_together={('organisation', 'iata')},
        ),
        migrations.AlterUniqueTogether(
            name='gridemissionfactor',
            unique_together={('organisation', 'country', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='plantlookup',
            unique_together={('organisation', 'werks_code')},
        ),
        migrations.AddIndex(
            model_name='saprow',
            index=models.Index(fields=['plant_code'], name='emissions_s_plant_c_c05810_idx'),
        ),
        migrations.AddIndex(
            model_name='saprow',
            index=models.Index(fields=['document_date'], name='emissions_s_documen_691c21_idx'),
        ),
        migrations.AddIndex(
            model_name='saprow',
            index=models.Index(fields=['esg_category'], name='emissions_s_esg_cat_8c9e60_idx'),
        ),
        migrations.AddIndex(
            model_name='saprow',
            index=models.Index(fields=['organisation'], name='emissions_s_organis_be1829_idx'),
        ),
        migrations.AddIndex(
            model_name='travelrow',
            index=models.Index(fields=['segment_type'], name='emissions_t_segment_45024f_idx'),
        ),
        migrations.AddIndex(
            model_name='travelrow',
            index=models.Index(fields=['travel_date'], name='emissions_t_travel__f1978d_idx'),
        ),
        migrations.AddIndex(
            model_name='travelrow',
            index=models.Index(fields=['traveller_email'], name='emissions_t_travell_2d8111_idx'),
        ),
        migrations.AddIndex(
            model_name='travelrow',
            index=models.Index(fields=['external_trip_id'], name='emissions_t_externa_bee8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='travelrow',
            index=models.Index(fields=['organisation'], name='emissions_t_organis_7f8149_idx'),
        ),
        migrations.AddIndex(
            model_name='utilityrow',
            index=models.Index(fields=['meter_id'], name='emissions_u_meter_i_99cb54_idx'),
        ),
        migrations.AddIndex(
            model_name='utilityrow',
            index=models.Index(fields=['period_month'], name='emissions_u_period__17642d_idx'),
        ),
        migrations.AddIndex(
            model_name='utilityrow',
            index=models.Index(fields=['organisation'], name='emissions_u_organis_eccb15_idx'),
        ),
    ]
