# Generated by Django 5.2.14 on 2026-05-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saprow',
            name='parse_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelrow',
            name='distance_source',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='travelrow',
            name='parse_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='utilityrow',
            name='parse_error',
            field=models.TextField(blank=True),
        ),
    ]
