# Generated by Django 5.2.14 on 2026-05-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0004_saprow_parse_error_travelrow_distance_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrow',
            name='emission_factor_used',
        ),
        migrations.AddField(
            model_name='saprow',
            name='emission_factor_source',
            field=models.CharField(blank=True, choices=[('DEFRA_2024', 'DEFRA 2024'), ('DESNZ_2024', 'DESNZ 2024'), ('IPCC_AR6', 'IPCC AR6'), ('ICAO_2023', 'ICAO 2023'), ('CUSTOM', 'Custom')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saprow',
            name='emission_factor_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saprow',
            name='emission_factor_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saprow',
            name='emission_factor_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saprow',
            name='ghg_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saprow',
            name='ghg_scope',
            field=models.CharField(blank=True, choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='travelrow',
            name='emission_factor_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelrow',
            name='emission_factor_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelrow',
            name='ghg_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travelrow',
            name='ghg_scope',
            field=models.CharField(blank=True, choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='utilityrow',
            name='emission_factor_source',
            field=models.CharField(blank=True, choices=[('DEFRA_2024', 'DEFRA 2024'), ('DESNZ_2024', 'DESNZ 2024'), ('IPCC_AR6', 'IPCC AR6'), ('ICAO_2023', 'ICAO 2023'), ('CUSTOM', 'Custom')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='utilityrow',
            name='emission_factor_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilityrow',
            name='emission_factor_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilityrow',
            name='emission_factor_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilityrow',
            name='ghg_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilityrow',
            name='ghg_scope',
            field=models.CharField(blank=True, choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='travelrow',
            name='emission_factor_source',
            field=models.CharField(blank=True, choices=[('DEFRA_2024', 'DEFRA 2024'), ('DESNZ_2024', 'DESNZ 2024'), ('IPCC_AR6', 'IPCC AR6'), ('ICAO_2023', 'ICAO 2023'), ('CUSTOM', 'Custom')], max_length=50, null=True),
        ),
    ]
