# Generated by Django 5.2.14 on 2026-05-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0005_remove_travelrow_emission_factor_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saprow',
            name='co2_comparison_status',
            field=models.CharField(blank=True, choices=[('NOT_APPLICABLE', 'Not Applicable'), ('MATCH', 'Match — variance < 5%'), ('MINOR_VARIANCE', 'Minor Variance — 5% to 15%'), ('MAJOR_VARIANCE', 'Major Variance — > 15%'), ('MISSING_DOC_VALUE', 'Missing Document Value')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='saprow',
            name='co2_variance_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saprow',
            name='document_claimed_co2_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saprow',
            name='emission_factor_record_id',
            field=models.UUIDField(blank=True, help_text='UUID of the EmissionFactor registry record used for this calculation', null=True),
        ),
        migrations.AddField(
            model_name='saprow',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saprow',
            name='system_calculated_co2_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelrow',
            name='emission_factor_record_id',
            field=models.UUIDField(blank=True, help_text='UUID of the EmissionFactor registry record used for this calculation', null=True),
        ),
        migrations.AddField(
            model_name='travelrow',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilityrow',
            name='co2_comparison_status',
            field=models.CharField(blank=True, choices=[('NOT_APPLICABLE', 'Not Applicable — no document CO2 claim'), ('MATCH', 'Match — variance < 5%'), ('MINOR_VARIANCE', 'Minor Variance — 5% to 15%'), ('MAJOR_VARIANCE', 'Major Variance — > 15%'), ('MISSING_DOC_VALUE', 'Missing Document Value')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='utilityrow',
            name='co2_variance_pct',
            field=models.FloatField(blank=True, help_text='abs((doc - system) / system) x 100', null=True),
        ),
        migrations.AddField(
            model_name='utilityrow',
            name='document_claimed_co2_kg',
            field=models.FloatField(blank=True, help_text='CO2 figure extracted directly from the utility bill document', null=True),
        ),
        migrations.AddField(
            model_name='utilityrow',
            name='emission_factor_record_id',
            field=models.UUIDField(blank=True, help_text='UUID of the EmissionFactor registry record used for this calculation', null=True),
        ),
        migrations.AddField(
            model_name='utilityrow',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilityrow',
            name='system_calculated_co2_kg',
            field=models.FloatField(blank=True, help_text='CO2 computed by the BreatheESG calculation engine', null=True),
        ),
    ]
