"""
apps/reports/models.py
======================
ForecastedEmissions — Stores algorithmic projections separately from actuals.
Auditors can always distinguish recorded data (SAPRow/UtilityRow/TravelRow)
from forward-looking statistical estimates stored here.
"""

import uuid
from django.db import models
from core.models import TenantModel


class ForecastedEmissions(TenantModel):
    """
    One record per (org, financial_year, month_number, scope).
    Generated by the forecast service layer; never edited manually.
    """

    class Scope(models.TextChoices):
        SCOPE_1 = 'SCOPE_1', 'Scope 1 — Direct (Fuel)'
        SCOPE_2 = 'SCOPE_2', 'Scope 2 — Electricity'
        SCOPE_3 = 'SCOPE_3', 'Scope 3 — Business Travel'

    class Method(models.TextChoices):
        RUN_RATE         = 'RUN_RATE',         'Annualized Run Rate'
        ETS              = 'ETS',              'Holt-Winters ETS'
        ACTIVITY_DRIVEN  = 'ACTIVITY_DRIVEN',  'Activity-Driven Projection'
        NOWCAST          = 'NOWCAST',          'Nowcast (proxy-estimated)'
        RUN_RATE_FALLBACK= 'RUN_RATE_FALLBACK','Run Rate (fallback — no prior FY)'
        INSUFFICIENT     = 'INSUFFICIENT',     'Insufficient Data'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Period identification
    financial_year  = models.CharField(max_length=10, db_index=True,
        help_text="India FY string, e.g. '2025-26'")
    month_number    = models.SmallIntegerField(
        help_text="1=Apr, 2=May, … 12=Mar (India FY calendar)")
    month_label     = models.CharField(max_length=7,
        help_text="ISO calendar month, e.g. '2025-09'")
    scope           = models.CharField(max_length=20, choices=Scope.choices, db_index=True)

    # Forecast values (all in metric tonnes CO₂e)
    co2e_tonnes_central = models.DecimalField(max_digits=14, decimal_places=6,
        help_text="Point estimate tCO₂e")
    co2e_tonnes_lower   = models.DecimalField(max_digits=14, decimal_places=6,
        null=True, blank=True, help_text="Lower bound of 90% CI")
    co2e_tonnes_upper   = models.DecimalField(max_digits=14, decimal_places=6,
        null=True, blank=True, help_text="Upper bound of 90% CI")

    # Forecast metadata
    forecast_method      = models.CharField(max_length=30, choices=Method.choices)
    confidence_pct       = models.SmallIntegerField(default=0,
        help_text="0–100 confidence score derived from RMSFE or variance")
    is_nowcast           = models.BooleanField(default=False,
        help_text="True = month estimated from proxy data, not observed actuals")
    rmsfe                = models.DecimalField(max_digits=10, decimal_places=6,
        null=True, blank=True, help_text="Root Mean Square Forecast Error for this scope")

    # What-if state captured at generation time
    activity_driver_air      = models.DecimalField(max_digits=6, decimal_places=4, default=0,
        help_text="ΔD applied to air travel (0 = no adjustment)")
    activity_driver_hotel    = models.DecimalField(max_digits=6, decimal_places=4, default=0)
    activity_driver_ground   = models.DecimalField(max_digits=6, decimal_places=4, default=0)

    # Audit trail
    generated_at     = models.DateTimeField(auto_now_add=True)
    generated_by_task = models.CharField(max_length=100, blank=True,
        help_text="Celery task ID or 'inline' for synchronous generation")

    class Meta:
        verbose_name        = 'Forecasted Emissions'
        verbose_name_plural = 'Forecasted Emissions'
        unique_together     = [('organisation', 'financial_year', 'month_number', 'scope')]
        ordering            = ['financial_year', 'month_number', 'scope']
        indexes = [
            models.Index(fields=['organisation', 'financial_year', 'scope']),
            models.Index(fields=['organisation', 'month_label', 'scope']),
        ]

    def __str__(self):
        return (f"[{self.scope}] {self.month_label} "
                f"= {self.co2e_tonnes_central} tCO₂e ({self.forecast_method})")
