# Generated by Django 5.2.14 on 2026-05-28 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastedEmissions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(db_index=True, help_text="India FY string, e.g. '2025-26'", max_length=10)),
                ('month_number', models.SmallIntegerField(help_text='1=Apr, 2=May, … 12=Mar (India FY calendar)')),
                ('month_label', models.CharField(help_text="ISO calendar month, e.g. '2025-09'", max_length=7)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 — Direct (Fuel)'), ('SCOPE_2', 'Scope 2 — Electricity'), ('SCOPE_3', 'Scope 3 — Business Travel')], db_index=True, max_length=20)),
                ('co2e_tonnes_central', models.DecimalField(decimal_places=6, help_text='Point estimate tCO₂e', max_digits=14)),
                ('co2e_tonnes_lower', models.DecimalField(blank=True, decimal_places=6, help_text='Lower bound of 90% CI', max_digits=14, null=True)),
                ('co2e_tonnes_upper', models.DecimalField(blank=True, decimal_places=6, help_text='Upper bound of 90% CI', max_digits=14, null=True)),
                ('forecast_method', models.CharField(choices=[('RUN_RATE', 'Annualized Run Rate'), ('ETS', 'Holt-Winters ETS'), ('ACTIVITY_DRIVEN', 'Activity-Driven Projection'), ('NOWCAST', 'Nowcast (proxy-estimated)'), ('RUN_RATE_FALLBACK', 'Run Rate (fallback — no prior FY)'), ('INSUFFICIENT', 'Insufficient Data')], max_length=30)),
                ('confidence_pct', models.SmallIntegerField(default=0, help_text='0–100 confidence score derived from RMSFE or variance')),
                ('is_nowcast', models.BooleanField(default=False, help_text='True = month estimated from proxy data, not observed actuals')),
                ('rmsfe', models.DecimalField(blank=True, decimal_places=6, help_text='Root Mean Square Forecast Error for this scope', max_digits=10, null=True)),
                ('activity_driver_air', models.DecimalField(decimal_places=4, default=0, help_text='ΔD applied to air travel (0 = no adjustment)', max_digits=6)),
                ('activity_driver_hotel', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('activity_driver_ground', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by_task', models.CharField(blank=True, help_text="Celery task ID or 'inline' for synchronous generation", max_length=100)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Forecasted Emissions',
                'verbose_name_plural': 'Forecasted Emissions',
                'ordering': ['financial_year', 'month_number', 'scope'],
                'indexes': [models.Index(fields=['organisation', 'financial_year', 'scope'], name='reports_for_organis_74e6a2_idx'), models.Index(fields=['organisation', 'month_label', 'scope'], name='reports_for_organis_6ebd4d_idx')],
                'unique_together': {('organisation', 'financial_year', 'month_number', 'scope')},
            },
        ),
    ]
