/**
 * BRSRReport.jsx — SEBI BRSR Core Summary Dashboard
 * Full-page BRSR compliance report with scope breakdown,
 * data quality dial, and CSV export.
 */
import { useState, useEffect } from 'react'
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, Cell
} from 'recharts'
import { FileDown, RefreshCw, ShieldCheck, AlertTriangle, CheckCircle2, Clock } from 'lucide-react'
import { getBRSRSummary } from '../../api/reports'

const CURRENT_FY = (() => {
  const now = new Date()
  const y = now.getMonth() >= 3 ? now.getFullYear() : now.getFullYear() - 1
  return `${y}-${String(y + 1).slice(2)}`
})()

const FY_OPTIONS = (() => {
  const options = [];
  const now = new Date();
  const currentY = now.getMonth() >= 3 ? now.getFullYear() : now.getFullYear() - 1;
  // Generate options from current year back to 2022
  for (let y = currentY; y >= 2022; y--) {
    options.push(`${y}-${String(y + 1).slice(2)}`);
  }
  return options;
})();

const SCOPE_COLORS = {
  'Scope 1': '#f97316',
  'Scope 2': '#3b82f6',
  'Scope 3': '#a855f7',
}

function Stat({ label, value, sub, icon: Icon, color = 'text-slate-800' }) {
  return (
    <div className="bg-white rounded-xl border border-slate-200 p-4 flex items-start gap-3">
      {Icon && (
        <div className="p-2 rounded-lg bg-slate-50 mt-0.5">
          <Icon size={18} className="text-slate-500" />
        </div>
      )}
      <div>
        <p className="text-xs text-slate-500 mb-0.5">{label}</p>
        <p className={`text-2xl font-bold ${color}`}>{value}</p>
        {sub && <p className="text-xs text-slate-400 mt-0.5">{sub}</p>}
      </div>
    </div>
  )
}

function QualityDial({ pct }) {
  const r = 40
  const circ = 2 * Math.PI * r
  const filled = ((pct || 0) / 100) * circ
  const color = pct >= 80 ? '#22c55e' : pct >= 60 ? '#f59e0b' : '#ef4444'

  return (
    <div className="flex flex-col items-center">
      <svg width="110" height="110" className="-rotate-90">
        <circle cx="55" cy="55" r={r} fill="none" stroke="#e2e8f0" strokeWidth="10" />
        <circle
          cx="55" cy="55" r={r} fill="none"
          stroke={color} strokeWidth="10"
          strokeDasharray={`${filled} ${circ}`}
          strokeLinecap="round"
          style={{ transition: 'stroke-dasharray 1s ease' }}
        />
      </svg>
      <div className="text-center -mt-14">
        <p className="text-3xl font-bold" style={{ color }}>{pct?.toFixed(1)}%</p>
        <p className="text-xs text-slate-500 mt-0.5">Complete</p>
      </div>
    </div>
  )
}

export default function BRSRReport() {
  const [fy, setFy]       = useState(CURRENT_FY)
  const [data, setData]   = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  const load = async () => {
    setLoading(true)
    setError(null)
    try {
      const res = await getBRSRSummary(fy)
      setData(res.data)
    } catch (e) {
      setError(e.response?.data?.error || 'Failed to load BRSR summary')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { load() }, [fy])

  const exportCSV = () => {
    if (!data) return
    const rows = [
      ['SEBI BRSR Core — Emissions Summary'],
      ['Organisation', data.organisation],
      ['Reporting Period', data.reporting_period],
      ['Generated At', data.generated_at],
      ['Generated By', data.generated_by],
      [],
      ['Scope', 'Total CO₂e (tCO₂e)', 'Approved Rows', 'Total Rows'],
      ['Scope 1 — Direct', data.scope_1.total_co2e_tonnes, data.scope_1.approved_row_count, data.scope_1.row_count],
      ['Scope 2 — Electricity', data.scope_2.total_co2e_tonnes, data.scope_2.approved_row_count, data.scope_2.row_count],
      ['Scope 3 — Travel', data.scope_3.total_co2e_tonnes, data.scope_3.approved_row_count, data.scope_3.row_count],
      ['TOTAL', data.total_co2e_tonnes, '', ''],
      [],
      ['Data Quality'],
      ['Completeness', `${data.data_quality.completeness_pct}%`],
      ['Rows pending approval', data.data_quality.rows_pending_approval],
      ['Major CO₂ variances', data.data_quality.rows_with_major_co2_variance],
      ['Unresolved findings', data.data_quality.rows_with_unresolved_findings],
    ]
    const csv = rows.map(r => r.join(',')).join('\n')
    const blob = new Blob([csv], { type: 'text/csv' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url
    a.download = `BRSR_${data.organisation}_${fy}.csv`
    a.click()
    URL.revokeObjectURL(url)
  }

  const chartData = data ? [
    { name: 'Scope 1', value: data.scope_1.total_co2e_tonnes },
    { name: 'Scope 2', value: data.scope_2.total_co2e_tonnes },
    { name: 'Scope 3', value: data.scope_3.total_co2e_tonnes },
  ] : []

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div className="flex items-center gap-2">
          <ShieldCheck size={22} className="text-emerald-600" />
          <div>
            <h2 className="text-lg font-bold text-slate-800">SEBI BRSR Core Report</h2>
            <p className="text-xs text-slate-500">Business Responsibility & Sustainability Reporting — GHG Disclosure</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <select
            value={fy}
            onChange={e => setFy(e.target.value)}
            className="input-field text-sm py-1.5 w-32"
          >
            {FY_OPTIONS.map(f => <option key={f}>{f}</option>)}
          </select>
          <button onClick={load} className="btn-secondary py-1.5" title="Refresh">
            <RefreshCw size={14} className={loading ? 'animate-spin' : ''} />
          </button>
          <button onClick={exportCSV} disabled={!data} className="btn-primary py-1.5">
            <FileDown size={14} />
            Export BRSR CSV
          </button>
        </div>
      </div>

      {error && (
        <div className="bg-rose-50 border border-rose-200 text-rose-700 px-4 py-3 rounded-lg text-sm">
          {error}
        </div>
      )}

      {loading && !data && (
        <div className="flex items-center justify-center h-40 text-slate-400 text-sm">
          Loading BRSR summary...
        </div>
      )}

      {data && (
        <>
          {/* Organisation + Period banner */}
          <div className="bg-gradient-to-r from-emerald-700 to-teal-600 rounded-xl p-5 text-white">
            <p className="text-sm opacity-80">Organisation</p>
            <p className="text-xl font-bold">{data.organisation}</p>
            <p className="text-sm opacity-70 mt-1">Reporting Period: FY {data.reporting_period}</p>
          </div>

          {/* Total + scope stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <Stat
              label="Total Emissions"
              value={`${Number(data.total_co2e_tonnes).toLocaleString('en-IN', { maximumFractionDigits: 1 })} tCO₂e`}
              sub="All scopes combined"
              icon={ShieldCheck}
            />
            <Stat
              label="Scope 1 — Direct"
              value={`${Number(data.scope_1.total_co2e_tonnes).toLocaleString('en-IN', { maximumFractionDigits: 1 })} t`}
              sub={`${data.scope_1.approved_row_count}/${data.scope_1.row_count} rows approved`}
              color="text-orange-600"
            />
            <Stat
              label="Scope 2 — Electricity"
              value={`${Number(data.scope_2.total_co2e_tonnes).toLocaleString('en-IN', { maximumFractionDigits: 1 })} t`}
              sub={`${data.scope_2.emission_factor_used ?? '—'} kg CO₂e/kWh (${data.scope_2.fy_factor_used})`}
              color="text-blue-600"
            />
            <Stat
              label="Scope 3 — Travel"
              value={`${Number(data.scope_3.total_co2e_tonnes).toLocaleString('en-IN', { maximumFractionDigits: 1 })} t`}
              sub={`${data.scope_3.approved_row_count}/${data.scope_3.row_count} rows approved`}
              color="text-purple-600"
            />
          </div>

          {/* Chart + Data Quality */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {/* Bar chart */}
            <div className="md:col-span-2 bg-white rounded-xl border border-slate-200 p-5">
              <p className="text-sm font-semibold text-slate-700 mb-4">Scope Breakdown (tCO₂e)</p>
              <ResponsiveContainer width="100%" height={180}>
                <BarChart data={chartData} barSize={48}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                  <XAxis dataKey="name" tick={{ fontSize: 12 }} />
                  <YAxis tick={{ fontSize: 11 }} />
                  <Tooltip
                    formatter={(v) => [`${Number(v).toLocaleString('en-IN', { maximumFractionDigits: 2 })} tCO₂e`]}
                    contentStyle={{ fontSize: 12 }}
                  />
                  <Bar dataKey="value" radius={[6, 6, 0, 0]}>
                    {chartData.map(entry => (
                      <Cell key={entry.name} fill={SCOPE_COLORS[entry.name]} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>

            {/* Data quality */}
            <div className="bg-white rounded-xl border border-slate-200 p-5">
              <p className="text-sm font-semibold text-slate-700 mb-3">Data Quality</p>
              <div className="flex justify-center mb-4">
                <QualityDial pct={data.data_quality.completeness_pct} />
              </div>
              <div className="space-y-2">
                {[
                  {
                    icon: Clock,
                    label: 'Pending approval',
                    value: data.data_quality.rows_pending_approval,
                    color: data.data_quality.rows_pending_approval > 0 ? 'text-amber-600' : 'text-emerald-600',
                  },
                  {
                    icon: AlertTriangle,
                    label: 'Major CO₂ variances',
                    value: data.data_quality.rows_with_major_co2_variance,
                    color: data.data_quality.rows_with_major_co2_variance > 0 ? 'text-rose-600' : 'text-emerald-600',
                  },
                  {
                    icon: CheckCircle2,
                    label: 'Unresolved findings',
                    value: data.data_quality.rows_with_unresolved_findings,
                    color: data.data_quality.rows_with_unresolved_findings > 0 ? 'text-rose-600' : 'text-emerald-600',
                  },
                ].map(({ icon: Icon, label, value, color }) => (
                  <div key={label} className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-1.5 text-slate-600">
                      <Icon size={12} />
                      <span>{label}</span>
                    </div>
                    <span className={`font-bold ${color}`}>{value}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Scope 2 Detail */}
          <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 text-sm">
            <p className="font-semibold text-blue-800 mb-1">Scope 2 — Methodology Note</p>
            <p className="text-blue-700 text-xs">
              Location-based method · Emission factor: <strong>{data.scope_2.emission_factor_used} kg CO₂e/kWh</strong> ·
              Source: <strong>CEA CO₂ Baseline Database V20.0 (FY {data.scope_2.fy_factor_used})</strong> ·
              Total consumption: <strong>{Number(data.scope_2.total_kwh_consumed).toLocaleString('en-IN')} kWh</strong>
            </p>
          </div>

          {/* Footer */}
          <p className="text-xs text-slate-400 text-center">
            Generated {data.generated_at} by {data.generated_by} · SEBI BRSR Core FY 2025-26 compliant
          </p>
        </>
      )}
    </div>
  )
}
