# Generated by Django 5.2.14 on 2026-05-26 16:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Flat File Export'), ('UTILITY', 'Utility Portal CSV'), ('TRAVEL', 'Concur / Navan Travel API')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='raw_uploads/')),
                ('original_filename', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded — awaiting processing'), ('PROCESSING', 'Processing in progress'), ('DONE', 'Parsing complete'), ('FAILED', 'Parsing failed')], db_index=True, default='UPLOADED', max_length=20)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Raw Upload',
                'verbose_name_plural': 'Raw Uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
