# Generated by Django 5.2.14 on 2026-05-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawupload',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded — awaiting processing'), ('PROCESSING', 'Processing in progress'), ('DONE', 'Parsing complete'), ('FAILED', 'Parsing failed'), ('OCR_EXTRACTED', 'AI OCR extracted — awaiting confirmation')], db_index=True, default='UPLOADED', max_length=20),
        ),
    ]
