# Generated by Django 5.2.14 on 2026-05-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_alter_rawupload_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=10, unique=True)),
                ('iata_code', models.CharField(blank=True, db_index=True, max_length=4, null=True)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('airport_type', models.CharField(max_length=50)),
                ('iso_country', models.CharField(max_length=2)),
                ('iso_region', models.CharField(max_length=10)),
                ('municipality', models.CharField(blank=True, max_length=255, null=True)),
                ('continent', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'ordering': ['ident'],
            },
        ),
    ]
