# Generated by Django 5.2.14 on 2026-05-28 07:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_auditlog_rowcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 — Direct'), ('SCOPE_2', 'Scope 2 — Electricity'), ('SCOPE_3', 'Scope 3 — Value Chain')], db_index=True, max_length=20)),
                ('fuel_or_activity_type', models.CharField(db_index=True, help_text='e.g. diesel, electricity_india, flight_short_haul, hotel_night', max_length=80)),
                ('factor_value', models.FloatField()),
                ('factor_unit', models.CharField(help_text="e.g. 'kg CO2e / litre' or 'kg CO2e / kWh'", max_length=100)),
                ('source_name', models.CharField(choices=[('CEA_V20', 'CEA CO2 Baseline Database V20.0'), ('IPCC_2006', 'IPCC 2006 Guidelines'), ('IPCC_AR6', 'IPCC AR6 (2021)'), ('DEFRA_2024', 'DEFRA / DESNZ 2024'), ('ICAO_2023', 'ICAO Carbon Emissions Calculator 2023'), ('INDIA_GHG', 'India GHG Program'), ('GHG_PROTOCOL', 'GHG Protocol Cross-Sector Tools')], max_length=30)),
                ('source_version', models.CharField(blank=True, max_length=50)),
                ('valid_from_fy', models.CharField(help_text="India FY e.g. '2024-25'", max_length=10)),
                ('valid_to_fy', models.CharField(blank=True, help_text='null = still current', max_length=10, null=True)),
                ('country_code', models.CharField(default='IN', max_length=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Emission Factor',
                'verbose_name_plural': 'Emission Factors',
                'ordering': ['-valid_from_fy', 'scope', 'fuel_or_activity_type'],
                'indexes': [models.Index(fields=['scope', 'fuel_or_activity_type', 'is_active'], name='ingestion_e_scope_6e0c57_idx')],
                'unique_together': {('scope', 'fuel_or_activity_type', 'valid_from_fy', 'country_code')},
            },
        ),
    ]
