# Generated by Django 5.2.14 on 2026-05-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0007_emissionfactor_registry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionfactor',
            name='fuel_or_activity_type',
            field=models.CharField(db_index=True, help_text='e.g. diesel, electricity_india, flight_short_haul, hotel_night', max_length=100),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='source_version',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
